name: Cypress end-to-end tests 🧪👷
on: 
  workflow_dispatch:

jobs:
  chrome:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-20.6.1-chrome-116.0.5845.187-1-ff-117.0-edge-116.0.1938.76-1
      options: --user 1001
    name: E2E on Chrome
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
      
      - name: Install Dependencies
        run: yarn install

      - name: Run E2E tests
        uses: cypress-io/github-action@v6
        with:
          build: yarn run build
          start: yarn start
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  firefox:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-20.6.1-chrome-116.0.5845.187-1-ff-117.0-edge-116.0.1938.76-1
      options: --user 1001
    name: E2E on Firefox
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Install Dependencies
        run: yarn install

      - name: Run E2E tests
        uses: cypress-io/github-action@v6
        with:
          build: yarn run build
          start: yarn start
          browser: firefox
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  edge:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-20.6.1-chrome-116.0.5845.187-1-ff-117.0-edge-116.0.1938.76-1
      options: --user 1001
    name: E2E on Edge
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Install Dependencies
        run: yarn install

      - name: Run E2E tests
        uses: cypress-io/github-action@v6
        with:
         build: yarn run build
         start: yarn start
         browser: edge
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  safari:
    runs-on: ubuntu-latest
    name: E2E on Webkit
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Install webkit dependencies on linux
        run: npx playwright install-deps webkit

      - name: Run E2E tests
        uses: cypress-io/github-action@v6
        with:
          build: yarn run build
          start: yarn start
          command: yarn cypress run --browser webkit
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
