name: Cypress end-to-end tests 🧪👷
on: [push]
jobs:
  chrome:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-18.15.0-chrome-111.0.5563.146-1-ff-111.0.1-edge-111.0.1661.62-1
      options: --user 1001
    name: E2E on Chrome
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
      
      - name: Install Dependencies
        run: yarn install

      - name: Run E2E tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
  firefox:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-18.15.0-chrome-111.0.5563.146-1-ff-111.0.1-edge-111.0.1661.62-1
      options: --user 1001
    name: E2E on Firefox
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Install Dependencies
        run: yarn install

      - name: Run E2E tests
      - uses: cypress-io/github-action@v5
        with:
         browser: firefox
  edge:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-18.15.0-chrome-111.0.5563.146-1-ff-111.0.1-edge-111.0.1661.62-1
      options: --user 1001
    name: E2E on Edge
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Install Dependencies
        run: yarn install

      - name: Run E2E tests
      - uses: cypress-io/github-action@v5
        with:
         browser: edge
  safari:
    runs-on: ubuntu-latest
    # container: 
    #   image: cypress/browsers:node-18.14.1-chrome-110.0.5481.96-1-ff-109.0-edge-110.0.1587.41-1
    #   options: --user 1001
    name: E2E on Webkit
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Install webkit dependencies on linux
        run: npx playwright install-deps webkit

      - name: Run E2E tests
      - uses: cypress-io/github-action@v5
        with:
         command: yarn cypress run --browser webkit
