name: Cypress end-to-end tests 🧪👷
on: 
  push:

jobs:
  chrome:
    runs-on: ubuntu-latest
    
    container: 
      image: cypress/browsers:latest
      options: --user 1001
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: yarn install

      - name: Run E2E tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECTID }}
  firefox:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:latest
      options: --user 1001
    name: E2E on Firefox
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install

      - name: Run E2E tests
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECTID }}
  edge:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:latest
      options: --user 1001
    name: E2E on Edge
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install

      - name: Run E2E tests
        uses: cypress-io/github-action@v6
        with:
          browser: edge
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECTID }}
  safari:
    runs-on: ubuntu-latest
    name: E2E on Webkit
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install webkit dependencies on linux
        run: npx playwright install-deps webkit

      - name: Run E2E tests
        uses: cypress-io/github-action@v6
        with:
          # build: npm run build
          # start: npm start
          command: yarn cypress run --browser webkit
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECTID }}
