name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node-18.14.1-chrome-110.0.5481.96-1-ff-109.0-edge-110.0.1587.41-1
    steps:
      - name: Get code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        uses: yarn install

      - name: Run E2E tests
        uses: cypress-io/github-action@v5
        with:
          build: yarn build
          start: yarn start